name: Run End to End Test

run-name: Run End to End Test

on:
  workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  run-end-to-end-test:

    # Runner will run with this OS
    runs-on: ubuntu-latest

    steps:

      - name: Checkout master branch of the repo
        uses: actions/checkout@v3

      - name: Ensure to cache Docker images
        uses: ScribeMD/docker-cache@0.2.6
        if: success() || failure()
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker/armseleniumgrid.yml') }}

      - name: Setup Selenium Grid (Hub and Nodes)
        run: docker compose -f docker/armseleniumgrid.yml up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          # Cache dependencies from pom.xml, reduces run time by only downloading new dependencies
          cache: 'maven'
#
      - name: Run EndToEnd Test
        run: mvn test

      - name: Get Allure history
        uses: actions/checkout@v3
        if: success() || failure()
        with:
          # The repo branch to checkout
          ref: test-report
          # Relative path under $GITHUB_WORKSPACE to place the repository branch that was checked out
          # $GITHUB_WORKSPACE is the default working directory on the runner for steps: /home/runner/work/gh-actions/gh-actions
          path: test-report

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: success() || failure()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: test-report
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      # Note that after this workflow, `pages-build-deployment` workflow controlled by GitHub still has to complete before the latest reports are published to GitHub Pages
      - name: Deploy report to Github Pages
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: test-report
          publish_dir: allure-history

      - name: Latest Report URL
        if: success() || failure()
        run: echo https://carlnoval.github.io/gh-gridwdckr/${{ github.run_number }}