name: name - Hello World Github Actions (optional)
run-name: run-name - GitHub Actions hello world (optional)
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
#      environment:
#        description: 'Environment to run tests against'
#        type: environment
#        required: true
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from GitHub Actions"